version: 0.1
phases:
  install:
    commands:
      - aws s3 cp ./LambdaCode/lambda_function.py s3://sandeep-lambda-pipeline/Lamdbacode/
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket sandeep-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
